import axios from "axios";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [url, setUrl] = useState("");
  const [url_hash, setUrl_hash] = useState("");
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleClick = async () => {
    setLoading(true);
    setSuccess(false);
    setError(false);
    const data = await axios.post(`/api/create`, {
      url,
      url_hash,
    });

    if (data.status === 200) setSuccess(true);
    else setError(true);
    setLoading(false);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Linkly</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <input
          onChange={(e) => setUrl(e.target.value)}
          value={url}
          type='text'
          placeholder='Enter your URL'
        />
        <input
          onChange={(e) => setUrl_hash(e.target.value)}
          value={url_hash}
          type='text'
          placeholder='Enter your URL Hash'
        />
        <button onClick={handleClick}>Shorten IT</button>
        {loading && <p>Loading</p>}
        {success && (
          <p>
            URL has been shortened. Go to{" "}
            <a
              href={`https://linkly.vercel.app/${url_hash}`}
              target='_blank'
              rel='noreferrer'
            >
              {`https://linkly.vercel.app/${url_hash}`}
            </a>
          </p>
        )}
        {error && <p>Something Went Wrong</p>}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
